server:
#   port: 8763
   port: 80
   context-path: /Shop
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
spring:
   freemarker:
      suffix: .ftl
      templateEncoding: UTF-8
      templateLoaderPath: classpath:/templates/
   mvc:
      view:
         prefix: /WEB-INF/
         suffix: .jsp
   application:
      name: shop
   redis:
      host: localhost
      password: 123456
      port: 6379
      pool:
         max-idle: 100
         min-idle: 1
         max-active: 1000
         max-wait: -1