server:
   port: 8762
   context-path: /member
eureka:
   client:
      serviceUrl: 
         defaultZone: http://localhost:8761/eureka/
spring:
   application:
      name: member
   redis:
      host: localhost
      password: 123457
      port: 6379
      pool:
         max-idle: 100
         min-idle: 1
         max-active: 1000
         max-wait: -11
   datasource:
        name: test
        url: jdbc:mysql://localhost:3306/shop
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
   activemq:
      broker-url: tcp://localhost:61616
      user: admin
      password: admin
message:
   queue: message_queue